version: "3"

services:
  db-stream:
    image: mysql:5.7
    restart: always
    container_name: db-stream
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_USER: stream
      MYSQL_PASSWORD: stream
      MYSQL_DATABASE: stream
      MYSQL_ROOT_PASSWORD: stream
    command: --innodb_use_native_aio=0 --socket=/tmp/mysql.sock --bind_address=0.0.0.0


volumes:
  mysql: